### ISSUE TITLE
Problems trying to build tony on Ubuntu, configure / subrepo references (?)

### ISSUE THREAD

**Issue by nullmightybofo** [sonic-visualiser/tony#2]
Hello!
I'd like to use Tony on Ubuntu 18.04.1. I followed the instructions here:
https://code.soundsoftware.ac.uk/projects/tony/wiki/Compiling_Tony

Sadly, running `./configure` fails with:
` dataquay                     | Failed      | Command failed: hg --config "ui.interactive=true" --config "ui.merge=:merge" clone -u default "https://hg.sr.ht/%7Ebreakfastquay/dataquay" dataquay (in dir /home/xxx/yyy/tony_hg/.)`,
and similar looking errors for bqvec, bqfft, bqresample, bqaudioio, bqaudiostream, bqthingfactory. It seems there is a problem with the cloning from these subrepos (? I am not sure I understand what is going on here).

Note the `%7E` string, in the URL, that should be a tilde `~`, I guess. Running the command in terminal with the fixed URL, e.g.:
`hg --config "ui.interactive=true" --config "ui.merge=:merge" clone -u default "https://hg.sr.ht/~breakfastquay/bqvec" bqvec`
yields this error: 

`abort: 'https://hg.sr.ht/~breakfastquay/bqvec' does not appear to be an hg repository:
---%<--- (text/html; charset=utf-8)
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="theme-color" content="#ffffff">
  <title>~breakfastquay/bqvec - sourcehut hg</title> ` 

(I cut a part from this) 

The other dependecies, e.g. vamp-plugin-sdk, svcore, svgui, etc., all come out OK.

I cloned the main repository using hg as well as git, I get the same errors in both cases. (I am not familiar with mercurial, so I tried the git repo first; I suspected the subrepo problem to have something to do with that, so I tried mercurial as well, to no avail.)

Any help and hints are highly appreciated. Thanks very much in advance!

**Comment by cannam** [comment]
This one is still a little bit up in the air, I'm afraid.

At the moment the only solution is to have a newer version of Mercurial installed on your system - version 4.7 or newer should work fine; unfortunately Ubuntu 18.04 has version 4.5 and this is not compatible with the subrepos as currently served via https from sr.ht.

The incompatibility is also being worked on at the hosting site, however, and I'm hoping that in no more than a few days the problem will be solved regardless of what version of Mercurial you have. If that doesn't happen, then I'll have to find an alternative approach.

**Comment by nullmightybofo** [comment]
Hey, thanks for getting back so quick! I will check if I can get a new version of mercurial for Ubuntu and report back if that helped. BR!

**Comment by nullmightybofo** [comment]
Ok, so I installed mercurial 5.1 from source, and configure worked, it did get the necessary subrepos. On to the next steps!

I consider this issue solved and will close it later today.
Thanks again and BR!

**Comment by FFYYang** [comment]
Hello, do you know how to use tony in the command line? ^_^
