### ISSUE TITLE
[question] using tony as a command line tool

### ISSUE THREAD

**Issue by levinericzimmermann** [sonic-visualiser/tony#3]
Hello everyone,

first of all thank you for this amazing software! It's super impressive how well the analysis is working.

Despite that I know that one of the key features of Tony is the GUI and the ability to manually edit and annotate the algorithmic analysis, I wondered if there is any way to analyses audio files and export the data through Tony without opening the GUI and with just calling the program over the command line? When calling Tony with the '--help' flag, I couldn't find any suitable option.

In my use case I have over hundred of short monophonic melodic phrases and would like to automate the generation of .svl files that contain the respective note data while still having access to the reliable techniques that Tony offers.

Best regards,

Levin

**Comment by FFYYang** [comment]
I have the same question, do you know how to do? ^_^

**Comment by levinericzimmermann** [comment]
@FFYYang I think it's not possible. But when rereading the documentation, I realized tony is simply a GUI / wrapper for the pYIN Vamp plugin. For the purpose of batch analysis they [developed another program 'sonic-annotator'](https://vamp-plugins.org/sonic-annotator/). I think this issue can therefore be closed.
